I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 196, in script
    with flash
  File "game/script.rpy", line 196, in <module>
    with flash
NameError: name 'flash' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 196, in script
    with flash
  File "/Users/helen.gezahegn/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 1367, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/Users/helen.gezahegn/Documents/renpy-8.3.7-sdk/renpy/python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/helen.gezahegn/Documents/renpy-8.3.7-sdk/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 196, in <module>
    with flash
NameError: name 'flash' is not defined

macOS-15.2-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
CHATBOTV1 1.0
Tue Apr 22 05:37:01 2025
